### ISSUE TITLE
新特性请求支持

### ISSUE THREAD

**Issue by qubbei** [wwhai/rulex#11]
## 1、网关支持采集不同PLC
- 网关能采集多台子设备(例:机床)，不同机床下有多个PLC，每个PLC走不同的采集协议.
- 例：xxx网关采集2台不同种类机床(A001、B001)，A001机床拥有2个PLC，其中一个PLC走Modbus协议，另一个走Tcp协议；B001机床跟A001情况类似。这个时候网关采集这四个PLC.

## 2、网关上报报文中子设备标识符
- 基于上面的【网关采集多种子设备】问题，网关如何动态去维护上报的数据报文是属于哪个子设备.

## 建议
- 网关有【通道】概念.
- 网关支持：子设备有【通讯地址(从机号)】概念.

**Comment by wwhai** [comment]
入 `0.2.0`

**Comment by wwhai** [comment]
## 网关支持采集不同设备
创建多个资源就可以实现监控不同的设备
![image](https://user-images.githubusercontent.com/20577297/149507743-0e29a33c-8aee-4fa9-9061-7cb812069e56.png)

## 网关上报报文中子设备标识符
可以配置tag来标识设备
![image](https://user-images.githubusercontent.com/20577297/149507703-e63a9736-62f6-42fc-b94a-64ba89db7da2.png)

## 网关有【通道】概念
`驱动` 就是通道

## 网关支持：子设备有【通讯地址(从机号)】概念.
Modbus 有从机地址

![image](https://user-images.githubusercontent.com/20577297/149507785-e3f82e96-7f12-4681-afe6-5b87f18fb23b.png)
![image](https://user-images.githubusercontent.com/20577297/149507814-d64b2ac2-6515-4c56-8be3-1de31d81cdb5.png)
